@baseUrl = http://localhost:3333/api
@authToken = eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJiZTE1OTJkZi0xOGY1LTRjYjMtYjMxOS1kNzg1ZDM3MGExMjIiLCJpYXQiOjE3NzEyNDg1MzEsImV4cCI6MTc3MTI1MjEzMX0.XalWPrYyj6vobgOB0RnKttyeUts0LWdbRL5B6PG3ktewq9c81ETM04SNgnxAfsfAHdlizKE7JEHbxe7cc59NSfvZg2pX9h3O4pihZl4qjzRjBN1AxCiWRBo5zZ9naES0PB0LfdIdKF74V8CYiJjbH6EK4GrQOCsFKdJRZty0xujzY371AWpahbzh-yU9tdw3D6u5ebCfCN0qLkVTD-okEd6ve0mcc6IyszX9Fuh1RxkJlptOEbg0ev0Mf1dRML4T7UE1aYeWxHYK4BFKsrUqS4osiudGjx0cpoOvb6bo2EKxiaVDUj8Ed3IA0MR7-EpNhX0uMra0LgOc_4VwChbNsg
@barbershopId = 29640943-b0f3-45be-85b1-9df879f891b6

### Login
POST {{baseUrl}}/auth/sessions
Content-Type: application/json

{
  "email": "diego@rocketseat.com.br",
  "password": "123456"
}

### Login BKO
POST {{baseUrl}}/backoffice/sessions
Content-Type: application/json

{
  "email": "diegobko@rocketseat2.com.br",
  "password": "123456"
}

### Cadastro
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
  "name": "Diego Fernandes",
  "email": "diego@rocketseat.com.br",
  "password": "123456"
}

### Cadastro BKO
POST {{baseUrl}}/backoffice/accounts
Content-Type: application/json

{
  "name": "Diego Fernandes BKO2",
  "email": "diegobko@rocketseat2.com.br",
  "password": "123456"
}

### Perfil do usuário
GET {{baseUrl}}/users/me
Authorization: Bearer {{authToken}}

### Criar barbearia
POST {{baseUrl}}/barbershops
Content-Type: application/json
Authorization: Bearer {{authToken}}

# {
#   "name": "Barbearia do Tiago",
#   "phone": "11999999999",
#   "address": "Rua A, 123",
#   "city": "São Paulo",
#   "state": "SP",
#   "description": "Descrição opcional",
#   "email": "contato@example.com",
#   "avatar": "https://i.pravatar.cc/150?img=2",
#   "zipCode": "01234-567",
#   "latitude": -23.55052,
#   "longitude": -46.633308
# }

{
  "name": "Barbearia do Lucas",
  "phone": "11999999998",
  "address": "Rua B, 123",
  "city": "Brasília",
  "state": "DF",
  "description": "Descrição opcional",
  "email": "contato@example.com",
  "avatar": "https://i.pravatar.cc/150?img=3",
  "zipCode": "01234-567",
  "latitude": -23.55052,
  "longitude": -46.633308
}

### Atualizar barbearia
PATCH {{baseUrl}}/barbershops/{{barbershopId}}
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "address": "Rua A, 1234"
}

### Buscar barbearia por ID
GET {{baseUrl}}/barbershops/{{barbershopId}}
Content-Type: application/json
Authorization: Bearer {{authToken}}

### Listar barbearias
GET {{baseUrl}}/barbershops
Content-Type: application/json
Authorization: Bearer {{authToken}}

### Deletar barbearia
DELETE {{baseUrl}}/barbershops/{{barbershopId}}
Content-Type: application/json
Authorization: Bearer {{authToken}}
