@baseUrl = http://localhost:3333/api

@authToken = 

@refreshToken = 

@barbershopId = 

### Login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "diego@rocketseat.com.br",
  "password": "123456"
}

### Login do barbeiro
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "joao@barbearia.com",
  "password": "123456"
}

### Refresh Token
POST {{baseUrl}}/auth/refresh
Cookie: refresh_token={{refreshToken}}

### Cadastro de usuário
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
  "name": "Diego Fernandes",
  "email": "diego@rocketseat.com.br",
  "password": "123456"
}

### Cadastro de barbeiro
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
  "name": "Barbearia do João",
  "email": "joao@barbearia.com",
  "password": "123456"
}

### Atualizar perfil
PATCH {{baseUrl}}/users/me
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
"name": "Diego Fernandes"
}

### Perfil do usuário
GET {{baseUrl}}/users/me
Content-Type: application/json
Authorization: Bearer {{authToken}}

### Criar barbearia
POST {{baseUrl}}/barbershops
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "name": "Barbearia do Lucas",
  "phone": "11999999998",
  "address": "Rua B, 123",
  "city": "Brasília",
  "state": "DF",
  "description": "Descrição opcional",
  "email": "contato@example.com",
  "avatar": "https://i.pravatar.cc/150?img=3",
  "zipCode": "01234-567",
  "latitude": -23.55052,
  "longitude": -46.633308
}

### Atualizar barbearia
PATCH {{baseUrl}}/barbershops/{{barbershopId}}
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "address": "Rua A, 1234"
}

### Buscar barbearia
GET {{baseUrl}}/barbershops/{{barbershopId}}
Content-Type: application/json
Authorization: Bearer {{authToken}}

### Listar barbearias
GET {{baseUrl}}/barbershops
Content-Type: application/json
Authorization: Bearer {{authToken}}

### Deletar barbearia
DELETE {{baseUrl}}/barbershops/{{barbershopId}}
Content-Type: application/json
Authorization: Bearer {{authToken}}
